name: Validate PR from task branch to develop branch

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - develop

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@main

    - name: Set up Xcode
      uses: ./.github/mini_flows/setup_xcode  

    - name: Install dependencies
      uses: ./.github/mini_flows/install_dependencies

    - name: Build project
      uses: ./.github/mini_flows/build_project  

    - name: Run tests
      uses: ./.github/mini_flows/run_tests  
    
    - name: Validate PR Title
      run: |
          PR_TITLE=${{ github.event.pull_request.title }}
          if [[ ! $PR_TITLE =~ ^SDK-[0-9]+ ]]; then
            echo "::warning ::Invalid PR title format. Please use 'SDK-{number}' format."
          fi
          
    - name: Validate PR Description
      uses: ./.github/mini_flows/validate_pr_description
   
   
