name: Release version to Pod
on:
  release:
    types:
      - created
      
jobs:
  build:
    runs-on: macos-latest
    
    steps:
     - name: Release to pod
       uses: ./.github/mini_flows/pod_release
